### ISSUE TITLE
Crash running on Mac OS X 12.4 M1 Pro

### ISSUE THREAD

**Issue by peasus** [nalepae/csv-plot#2]
This occurs using the defaults listed on the web page.  (example data and the configuration-1.yaml file)

Also, thanks for this tool!  This looks super awesome!

Process CSV file... Traceback (most recent call last):
  File "/opt/homebrew/bin/csv-plot", line 8, in <module>
    sys.exit(app())
  File "/opt/homebrew/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/homebrew/lib/python3.9/site-packages/csv_plot/entrypoint.py", line 279, in main
    pad_and_sample(csv_path, FILES_DIR, x, cpu_count())
  File "/opt/homebrew/lib/python3.9/site-packages/csv_plot/csv/pad_and_sample.py", line 336, in pad_and_sample
    sample_sampled_to_the_end(nb_workers, dir_path, 1)
  File "/opt/homebrew/lib/python3.9/site-packages/csv_plot/csv/pad_and_sample.py", line 283, in sample_sampled_to_the_end
    sample_sampled_to_the_end(nb_workers, sampled_global_dir, index + 1)
  File "/opt/homebrew/lib/python3.9/site-packages/csv_plot/csv/pad_and_sample.py", line 283, in sample_sampled_to_the_end
    sample_sampled_to_the_end(nb_workers, sampled_global_dir, index + 1)
  File "/opt/homebrew/lib/python3.9/site-packages/csv_plot/csv/pad_and_sample.py", line 283, in sample_sampled_to_the_end
    sample_sampled_to_the_end(nb_workers, sampled_global_dir, index + 1)
  [Previous line repeated 2 more times]
  File "/opt/homebrew/lib/python3.9/site-packages/csv_plot/csv/pad_and_sample.py", line 262, in sample_sampled_to_the_end
    if are_files_fully_sampled(current_sampled_dir):
  File "/opt/homebrew/lib/python3.9/site-packages/csv_plot/csv/pad_and_sample.py", line 79, in are_files_fully_sampled
    next(lines)
StopIteration

**Comment by ncdm-stldr** [comment]
I have the same issue but in a different device: lenovo ideapad 5 duet. Is also achitecture: aarch64.

I added `print(path)` in `are_files_fully_sampled` method to see what file caused the issue. Is `/home/myname/.config/csv-plot/files/195cb3147d50143fa8cee9ce54d9fa4f/7_sampled/0.csv` in my case. It contains only one line which is `index,-0.725000,1.225000,-0.750000,1.300000,-0.827749,1.284223,-0.855667,1.387764`

It should normally contain more than one line I guess.

**Comment by ncdm-stldr** [comment]
It seems I can pass this step if I replace `cpu_count()` by `1` in `csv_plot/entrypoint.py`. (I also needed the cache with `rm -rf /home/myname/.config/csv-plot/`).
